env:
  node: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'airbnb-base'
  - 'airbnb-typescript/base'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 15
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - 'eslint-plugin-node'
rules: {
  no-console: [0]
}
